name: contact
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.2.0
  scoped_model: ^2.0.0
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  sembast: ^3.8.4+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
